/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MyAside: typeof import('./components/MyAside/index.vue')['default']
    MyHeader: typeof import('./components/MyHeader/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestChartDemo: typeof import('./components/TestChartDemo/index.vue')['default']
    TestStoreDemo: typeof import('./components/TestStoreDemo/index.vue')['default']
  }
}
